-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.AcceptTransactionsResult exposing (acceptedIds, failedIds)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


acceptedIds : SelectionSet (List Int) Api.Object.AcceptTransactionsResult
acceptedIds =
    Object.selectionForField "(List Int)" "acceptedIds" [] (Decode.int |> Decode.list)


failedIds : SelectionSet (List Int) Api.Object.AcceptTransactionsResult
failedIds =
    Object.selectionForField "(List Int)" "failedIds" [] (Decode.int |> Decode.list)
