-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.CheckSessionResult exposing (email, id, inboxSize, name)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


email : SelectionSet String Api.Object.CheckSessionResult
email =
    Object.selectionForField "String" "email" [] Decode.string


id : SelectionSet Int Api.Object.CheckSessionResult
id =
    Object.selectionForField "Int" "id" [] Decode.int


inboxSize : SelectionSet Int Api.Object.CheckSessionResult
inboxSize =
    Object.selectionForField "Int" "inboxSize" [] Decode.int


name : SelectionSet String Api.Object.CheckSessionResult
name =
    Object.selectionForField "String" "name" [] Decode.string
