-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.UserTransaction exposing (acceptanceIds, amount, beneficientIds, beneficients, description, id, insertedAt, payorId, tags)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


acceptanceIds : SelectionSet (List Int) Api.Object.UserTransaction
acceptanceIds =
    Object.selectionForField "(List Int)" "acceptanceIds" [] (Decode.int |> Decode.list)


amount : SelectionSet Int Api.Object.UserTransaction
amount =
    Object.selectionForField "Int" "amount" [] Decode.int


beneficientIds : SelectionSet (List Int) Api.Object.UserTransaction
beneficientIds =
    Object.selectionForField "(List Int)" "beneficientIds" [] (Decode.int |> Decode.list)


beneficients : SelectionSet decodesTo Api.Object.User -> SelectionSet (List decodesTo) Api.Object.UserTransaction
beneficients object_ =
    Object.selectionForCompositeField "beneficients" [] object_ (identity >> Decode.list)


description : SelectionSet (Maybe String) Api.Object.UserTransaction
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


id : SelectionSet Int Api.Object.UserTransaction
id =
    Object.selectionForField "Int" "id" [] Decode.int


insertedAt : SelectionSet Api.ScalarCodecs.Date Api.Object.UserTransaction
insertedAt =
    Object.selectionForField "ScalarCodecs.Date" "insertedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDate |> .decoder)


payorId : SelectionSet Int Api.Object.UserTransaction
payorId =
    Object.selectionForField "Int" "payorId" [] Decode.int


tags : SelectionSet (List String) Api.Object.UserTransaction
tags =
    Object.selectionForField "(List String)" "tags" [] (Decode.string |> Decode.list)
