-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.BalanceToOtherUser exposing (authoredByMeCount, authoredByOtherUserCount, iHaveMore, lastUpdateAt, otherUser, otherUserId, selection, sharedPaymentCount, transferCount, unseenForMeCount, unseenForOtherUserCount, value)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.BalanceToOtherUser
selection constructor =
    Object.selection constructor


authoredByMeCount : Field Int Api.Object.BalanceToOtherUser
authoredByMeCount =
    Object.fieldDecoder "authoredByMeCount" [] Decode.int


authoredByOtherUserCount : Field Int Api.Object.BalanceToOtherUser
authoredByOtherUserCount =
    Object.fieldDecoder "authoredByOtherUserCount" [] Decode.int


iHaveMore : Field Bool Api.Object.BalanceToOtherUser
iHaveMore =
    Object.fieldDecoder "iHaveMore" [] Decode.bool


lastUpdateAt : Field Api.Scalar.Date Api.Object.BalanceToOtherUser
lastUpdateAt =
    Object.fieldDecoder "lastUpdateAt" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Date)


otherUser : SelectionSet decodesTo Api.Object.User -> Field decodesTo Api.Object.BalanceToOtherUser
otherUser object_ =
    Object.selectionField "otherUser" [] object_ identity


otherUserId : Field Int Api.Object.BalanceToOtherUser
otherUserId =
    Object.fieldDecoder "otherUserId" [] Decode.int


sharedPaymentCount : Field Int Api.Object.BalanceToOtherUser
sharedPaymentCount =
    Object.fieldDecoder "sharedPaymentCount" [] Decode.int


transferCount : Field Int Api.Object.BalanceToOtherUser
transferCount =
    Object.fieldDecoder "transferCount" [] Decode.int


unseenForMeCount : Field Int Api.Object.BalanceToOtherUser
unseenForMeCount =
    Object.fieldDecoder "unseenForMeCount" [] Decode.int


unseenForOtherUserCount : Field Int Api.Object.BalanceToOtherUser
unseenForOtherUserCount =
    Object.fieldDecoder "unseenForOtherUserCount" [] Decode.int


value : Field Float Api.Object.BalanceToOtherUser
value =
    Object.fieldDecoder "value" [] Decode.float
