-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.SignInResult exposing (email, id, inboxSize, name, selection)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.SignInResult
selection constructor =
    Object.selection constructor


email : Field String Api.Object.SignInResult
email =
    Object.fieldDecoder "email" [] Decode.string


id : Field Int Api.Object.SignInResult
id =
    Object.fieldDecoder "id" [] Decode.int


inboxSize : Field Int Api.Object.SignInResult
inboxSize =
    Object.fieldDecoder "inboxSize" [] Decode.int


name : Field String Api.Object.SignInResult
name =
    Object.fieldDecoder "name" [] Decode.string
