-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.User exposing (balances, email, id, name, selection, transactions)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.User
selection constructor =
    Object.selection constructor


balances : SelectionSet decodesTo Api.Object.BalanceToOtherUser -> Field (List decodesTo) Api.Object.User
balances object_ =
    Object.selectionField "balances" [] object_ (identity >> Decode.list)


email : Field String Api.Object.User
email =
    Object.fieldDecoder "email" [] Decode.string


id : Field Int Api.Object.User
id =
    Object.fieldDecoder "id" [] Decode.int


name : Field String Api.Object.User
name =
    Object.fieldDecoder "name" [] Decode.string


transactions : SelectionSet decodesTo Api.Object.UserTransaction -> Field (List decodesTo) Api.Object.User
transactions object_ =
    Object.selectionField "transactions" [] object_ (identity >> Decode.list)
