version: '3.2'

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fundshare_prod
    volumes:
      - pgdata:/var/lib/postgresql/

  web:
    build: .
    ports:
      - "127.0.0.1:8080:5000"
    links:
      - "db:database"
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
