-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.BalanceToOtherUser exposing (authoredByMeCount, authoredByOtherUserCount, iHaveMore, inboxForMeCount, inboxForOtherUserCount, lastUpdateAt, otherUser, otherUserId, sharedPaymentCount, transferCount, value)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


authoredByMeCount : SelectionSet Int Api.Object.BalanceToOtherUser
authoredByMeCount =
    Object.selectionForField "Int" "authoredByMeCount" [] Decode.int


authoredByOtherUserCount : SelectionSet Int Api.Object.BalanceToOtherUser
authoredByOtherUserCount =
    Object.selectionForField "Int" "authoredByOtherUserCount" [] Decode.int


iHaveMore : SelectionSet Bool Api.Object.BalanceToOtherUser
iHaveMore =
    Object.selectionForField "Bool" "iHaveMore" [] Decode.bool


inboxForMeCount : SelectionSet Int Api.Object.BalanceToOtherUser
inboxForMeCount =
    Object.selectionForField "Int" "inboxForMeCount" [] Decode.int


inboxForOtherUserCount : SelectionSet Int Api.Object.BalanceToOtherUser
inboxForOtherUserCount =
    Object.selectionForField "Int" "inboxForOtherUserCount" [] Decode.int


lastUpdateAt : SelectionSet Api.ScalarCodecs.Date Api.Object.BalanceToOtherUser
lastUpdateAt =
    Object.selectionForField "ScalarCodecs.Date" "lastUpdateAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDate |> .decoder)


otherUser : SelectionSet decodesTo Api.Object.User -> SelectionSet decodesTo Api.Object.BalanceToOtherUser
otherUser object_ =
    Object.selectionForCompositeField "otherUser" [] object_ identity


otherUserId : SelectionSet Int Api.Object.BalanceToOtherUser
otherUserId =
    Object.selectionForField "Int" "otherUserId" [] Decode.int


sharedPaymentCount : SelectionSet Int Api.Object.BalanceToOtherUser
sharedPaymentCount =
    Object.selectionForField "Int" "sharedPaymentCount" [] Decode.int


transferCount : SelectionSet Int Api.Object.BalanceToOtherUser
transferCount =
    Object.selectionForField "Int" "transferCount" [] Decode.int


value : SelectionSet Float Api.Object.BalanceToOtherUser
value =
    Object.selectionForField "Float" "value" [] Decode.float
