-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.User exposing (TransactionsOptionalArguments, balances, email, id, name, selection, transactions)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.User
selection constructor =
    Object.selection constructor


balances : SelectionSet decodesTo Api.Object.BalanceToOtherUser -> Field (List decodesTo) Api.Object.User
balances object_ =
    Object.selectionField "balances" [] object_ (identity >> Decode.list)


email : Field String Api.Object.User
email =
    Object.fieldDecoder "email" [] Decode.string


id : Field Int Api.Object.User
id =
    Object.fieldDecoder "id" [] Decode.int


name : Field String Api.Object.User
name =
    Object.fieldDecoder "name" [] Decode.string


type alias TransactionsOptionalArguments =
    { offset : OptionalArgument Int, limit : OptionalArgument Int }


{-| Transactions for which this user was a payor or a beneficient
-}
transactions : (TransactionsOptionalArguments -> TransactionsOptionalArguments) -> SelectionSet decodesTo Api.Object.UserTransaction -> Field (List decodesTo) Api.Object.User
transactions fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { offset = Absent, limit = Absent }

        optionalArgs =
            [ Argument.optional "offset" filledInOptionals.offset Encode.int, Argument.optional "limit" filledInOptionals.limit Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionField "transactions" optionalArgs object_ (identity >> Decode.list)
