-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Scalar exposing (Date(..), Id(..), Uri(..))


type Date
    = Date String


type Id
    = Id String


type Uri
    = Uri String
