-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (AcceptTransactionsRequiredArguments, AddTransactionOptionalArguments, AddTransactionRequiredArguments, EditTransactionOptionalArguments, EditTransactionRequiredArguments, RegisterUserRequiredArguments, SignInRequiredArguments, acceptTransactions, addTransaction, checkSession, editTransaction, registerUser, signIn, signOut)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias AcceptTransactionsRequiredArguments =
    { transactionIds : List Int }


{-| Accept transactions added by someone else
-}
acceptTransactions : AcceptTransactionsRequiredArguments -> SelectionSet decodesTo Api.Object.AcceptTransactionsResult -> SelectionSet (Maybe decodesTo) RootMutation
acceptTransactions requiredArgs object_ =
    Object.selectionForCompositeField "acceptTransactions" [ Argument.required "transactionIds" requiredArgs.transactionIds (Encode.int |> Encode.list) ] object_ (identity >> Decode.nullable)


type alias AddTransactionOptionalArguments =
    { description : OptionalArgument String }


type alias AddTransactionRequiredArguments =
    { payorId : Int
    , beneficientIds : List Int
    , amount : Int
    , tags : List String
    }


{-| Remember transaction between payor and beneficients, then update the balance
-}
addTransaction : (AddTransactionOptionalArguments -> AddTransactionOptionalArguments) -> AddTransactionRequiredArguments -> SelectionSet decodesTo Api.Object.UserTransaction -> SelectionSet decodesTo RootMutation
addTransaction fillInOptionals requiredArgs object_ =
    let
        filledInOptionals =
            fillInOptionals { description = Absent }

        optionalArgs =
            [ Argument.optional "description" filledInOptionals.description Encode.string ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "addTransaction" (optionalArgs ++ [ Argument.required "payorId" requiredArgs.payorId Encode.int, Argument.required "beneficientIds" requiredArgs.beneficientIds (Encode.int |> Encode.list), Argument.required "amount" requiredArgs.amount Encode.int, Argument.required "tags" requiredArgs.tags (Encode.string |> Encode.list) ]) object_ identity


{-| Check who is signed in based on httponly safe cookies
-}
checkSession : SelectionSet decodesTo Api.Object.CheckSessionResult -> SelectionSet (Maybe decodesTo) RootMutation
checkSession object_ =
    Object.selectionForCompositeField "checkSession" [] object_ (identity >> Decode.nullable)


type alias EditTransactionOptionalArguments =
    { payorId : OptionalArgument Int
    , beneficientIds : OptionalArgument (List Int)
    , amount : OptionalArgument Int
    , tags : OptionalArgument (List String)
    , description : OptionalArgument String
    }


type alias EditTransactionRequiredArguments =
    { id : Int }


{-| Edit the transaction, change the acceptance ids (who will see the transaction in Inbox), then update the balance
-}
editTransaction : (EditTransactionOptionalArguments -> EditTransactionOptionalArguments) -> EditTransactionRequiredArguments -> SelectionSet decodesTo Api.Object.UserTransaction -> SelectionSet decodesTo RootMutation
editTransaction fillInOptionals requiredArgs object_ =
    let
        filledInOptionals =
            fillInOptionals { payorId = Absent, beneficientIds = Absent, amount = Absent, tags = Absent, description = Absent }

        optionalArgs =
            [ Argument.optional "payorId" filledInOptionals.payorId Encode.int, Argument.optional "beneficientIds" filledInOptionals.beneficientIds (Encode.int |> Encode.list), Argument.optional "amount" filledInOptionals.amount Encode.int, Argument.optional "tags" filledInOptionals.tags (Encode.string |> Encode.list), Argument.optional "description" filledInOptionals.description Encode.string ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "editTransaction" (optionalArgs ++ [ Argument.required "id" requiredArgs.id Encode.int ]) object_ identity


type alias RegisterUserRequiredArguments =
    { email : String
    , name : String
    , passwordHash : String
    }


{-| Register a new user
-}
registerUser : RegisterUserRequiredArguments -> SelectionSet decodesTo Api.Object.RegisterUserResult -> SelectionSet decodesTo RootMutation
registerUser requiredArgs object_ =
    Object.selectionForCompositeField "registerUser" [ Argument.required "email" requiredArgs.email Encode.string, Argument.required "name" requiredArgs.name Encode.string, Argument.required "passwordHash" requiredArgs.passwordHash Encode.string ] object_ identity


type alias SignInRequiredArguments =
    { email : String
    , passwordHash : String
    }


{-| Sign in user of given email with a password

  - passwordHash - md5 hashed password where salt (added on the right) is login email

-}
signIn : SignInRequiredArguments -> SelectionSet decodesTo Api.Object.SignInResult -> SelectionSet decodesTo RootMutation
signIn requiredArgs object_ =
    Object.selectionForCompositeField "signIn" [ Argument.required "email" requiredArgs.email Encode.string, Argument.required "passwordHash" requiredArgs.passwordHash Encode.string ] object_ identity


{-| Sign out current user
-}
signOut : SelectionSet decodesTo Api.Object.SignOutResult -> SelectionSet decodesTo RootMutation
signOut object_ =
    Object.selectionForCompositeField "signOut" [] object_ identity
