-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (AcceptTransactionsResult(..), BalanceToOtherUser(..), CheckSessionResult(..), RegisterUserResult(..), SignInResult(..), SignOutResult(..), User(..), UserTransaction(..))


type AcceptTransactionsResult
    = AcceptTransactionsResult


type BalanceToOtherUser
    = BalanceToOtherUser


type CheckSessionResult
    = CheckSessionResult


type RegisterUserResult
    = RegisterUserResult


type SignInResult
    = SignInResult


type SignOutResult
    = SignOutResult


type User
    = User


type UserTransaction
    = UserTransaction
